services:
  backend:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/pokemontcg
      - SPRING_DATASOURCE_USERNAME=ia
      - SPRING_DATASOURCE_PASSWORD=foufafou
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create  # Changé de "update" à "create"
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED=false
    volumes:
      - images-data:/app/images

  frontend:
    build: ./src/main/frontend
    ports:
      - "8082:80"

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=foufafou
      - MYSQL_DATABASE=pokemontcg
      - MYSQL_USER=ia
      - MYSQL_PASSWORD=foufafou
    ports:
      - "3309:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "test -S /run/mysqld/mysqld.sock"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mariadb-data:
  images-data: